# Exclude all private GitHub links
exclude = ['github\.com/private-org/.*', 'file:///home/runner/work/issues']

# Retry timeouts
timeout = 10
max_retries = 3

# Cache responses to speed up checks
cache = true