name: Check Links

on:
  # Run on pull requests
  pull_request:
    branches:
      - main
  # Run on schedule every week
  schedule:
    - cron: '0 0 * * 0'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' --output lychee.md
          fail: true
          format: markdown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue on Link Check Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const checkOutput = fs.readFileSync('lychee.md', 'utf8');
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: '🔗 Broken links detected',
              body: `Link checker detected broken links:\n\n${checkOutput}`,
              labels: ['broken-links']
            });