name: Broken Link Check

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs monthly on the 1st
  workflow_dispatch:      # Allows manual trigger
  push:
    branches:
      - main            # Runs on push to main branch
  pull_request:         # Runs on pull requests
    types: [opened, synchronize]

jobs:
  check-links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    
    steps:
      - name: Broken Link Checker
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: 'https://github.com/${{ github.repository }}'
          RECURSIVE: true
          TITLE: 'Broken Link Found: ${URL}'
          BODY: |
            ## Broken Link Report
            - **URL**: ${URL}
            - **Status Code**: ${STATUS}
            - **Parent URL**: ${PARENT}
            - **Check Time**: ${DATE}
            
            Please verify and fix this broken link.
          
          LABELS: 'broken-link,bug'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}