name: PR Label Lint

on:
  push:
    branches:
    - "!main"
  pull_request:
    branches:
    - "main"
    types: [labeled, unlabeled, opened, edited, synchronize]

concurrency:
  group: scan-labels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enforce:
    runs-on: ubuntu-latest
    name: Check Labels

    permissions:
      contents: read

    steps:
    - uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024 # 2.2.2
      with:
        REQUIRED_LABELS_ANY: "feature,bug,test,enhancement,documentation,chore,tech-debt"
        BANNED_LABELS: "needs-docs,needs-tests,needs-design,needs-git-sign-off,blocked,duplicate,invalid,wontfix"