name: Check Links

on:
  # Run on pull requests
  pull_request:
    branches:
      - main
  # Run on schedule every week
  schedule:
    - cron: '0 18 * * 0' # 6pm every Sunday
  # Allow manual trigger
  workflow_dispatch:

jobs:
  linkChecker:
    name: Check Links
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write # required to create issues
    steps:
    - name: Checkout
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67 # for v2.0.0

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # for v5.0.1
      with:
        title: '🔗 Broken links detected'
        content-filepath: ./lychee/out.md
        labels: broken-link, automated issue