name: Secret Scanning

on: pull_request

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    name: Secret Scanning

    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@1aa1871f9ae24a8c8a3a48a9345514acf42beb39 # v3.82.13
      with:
        extra_args: --only-verified
